### ISSUE TITLE
testscript: add support for the txtar file extension

### ISSUE THREAD

**Issue by myitcv** [rogpeppe/go-internal#126]
Currently, [`testscript`](https://github.com/rogpeppe/go-internal/blob/dc4b49510d96256f881880b9802536a6a70edfcc/testscript/testscript.go#L194) is hard-coded to only look for `.txt` files.

This is unfortunate, because `.txtar` is a more descriptive extension that would better lend itself to automatic syntax highlighting (on GitHub) etc. 

Opening this issue to capture the options for changing/extending this:

1. switch the default to search for `.txt` and `.txtar`
2. make it configurable via `testscript.Params`
3. ...

**Comment by mvdan** [comment]
I personally vote for option 1 - to just change the behavior. I'd be incredibly surprised if it broke any existing programs/tests. I understand the current semantics to be "load all txtar files in the provided directory", not "load all files in the provided directory with the txt extension". Arguably, using `.txt` instead of `.txtar` was a bit of a mistake early on.

**Comment by mvdan** [comment]
As a bit of an update: I propose that the tools use `*.txtar` by default - for example, txtar-addmod would now produce a `*.txtar` rather than a `*.txt` file. All code that globs would look for both extensions - which is arguably a bit cumbersome, as we can't do something like `txt(ar)?` with globbing, so we'd have to do our own little wrapper to read a directory and filter by either extension. But it's doable.

Then none of the existing users should break, new code would naturally gravitate towards using `*.txtar`, and we could start using it in our projects without needing new API.

@rogpeppe @myitcv thoughts? I'd like to make this transition happen in my repos and am happy to implement it here :)

**Comment by myitcv** [comment]
I'm happy with that suggestion.

**Comment by rogpeppe** [comment]
Yeah, I've thought for a while that `.txtar` would be a better extension.
